name: Rust cargo multi-platform tests & builds

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
  build:
    name: cargo build --release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            separator: \
            extension: .exe
          - os: windows-latest
            target: i686-pc-windows-msvc
            separator: \
            extension: .exe
          - os: macos-latest
            target: x86_64-apple-darwin
            separator: /
            extension: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            separator: /
            extension: ""
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            separator: /
            extension: ""
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabi
            separator: /
            extension: ""
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Add 32 bits support
        if: ${{ matrix.target == 'i686-unknown-linux-gnu' }}
        run: sudo dpkg --add-architecture i386
      - name: Add 32 bits support
        if: ${{ matrix.target == 'i686-unknown-linux-gnu' }}
        run: sudo apt-get update
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: castor_whispers-${{ matrix.target }}${{ matrix.extension }}
          path: target${{ matrix.separator }}${{ matrix.target }}${{ matrix.separator }}release${{ matrix.separator }}castor_whispers${{ matrix.extension }}
